/*
 COLLECTION
 */

export const LOAD_COLLECTION_SUCCESS = 'LOAD_COLLECTION_SUCCESS';
export const LOAD_COLLECTION_ERROR = 'LOAD_COLLECTION_ERROR';
export const ADD_BEER_SUCCESS = 'ADD_BEER_SUCCESS';
export const ADD_BEER_ERROR = 'ADD_BEER_ERROR';
export const EDIT_BEER = 'EDIT_BEER';
export const DELETE_BEER = 'DELETE_BEER';

/*
 NAVIGATION
 */

export const SET_CURRENT_BEER = 'SET_CURRENT_BEER';
export const RESET_CURRENT_BEER = 'RESET_CURRENT_BEER';
